NORMALIZE <- function(df) {
  df %>%
    mutate(
      COMUNE = case_when(
        COMUNE %in% c("GRESSONEY-LA-TRINITE'") ~ "GRESSONEY-LA-TRINITE",
        COMUNE %in% c("AGLIE'") ~ "AGLIE",
        COMUNE %in% c("ALI'") ~ "ALI",
        COMUNE %in% c("ALI' TERME") ~ "ALI TERME",
        COMUNE %in% c("AGLIE'") ~ "AGLIE",
        COMUNE %in% c("ARQUA' PETRARCA") ~ "ARQUA PETRARCA",
        COMUNE %in% c("ARQUA' POLESINE") ~ "ARQUA POLESINE",
        COMUNE %in% c("ARSIE'") ~ "ARSIE",
        COMUNE %in% c("BASCAPE'") ~ "BASCAPE",
        COMUNE %in% c("BASELGA DI PINE'") ~ "BASELGA DI PINE",
        COMUNE %in% c("BASICO'") ~ "BASICO",
        COMUNE %in% c("BASTIA MONDOVI'") ~ "BASTIA MONDOVI",
        COMUNE %in% c("BELVI'") ~ "BELVI",
        COMUNE %in% c("BIANZE'") ~ "BIANZE",
        COMUNE %in% c("BIDONI'") ~ "BIDONI",
        COMUNE %in% c("BUDDUSO'") ~ "BUDDUSO",
        COMUNE %in% c("CAGNO'") ~ "CAGNO",
        COMUNE %in% c("CANICATTI'") ~ "CANICATTI",
        COMUNE %in% c("CANTU'") ~ "CANTU",
        COMUNE %in% c("CARDE'") ~ "CARDE",
        COMUNE %in% c("CARRE'") ~ "CARRE",
        COMUNE %in% c("CARRU'") ~ "CARRU",
        COMUNE %in% c("CASTEL SAN NICCOLO'") ~ "CASTEL SAN NICCOLO",
        COMUNE %in% c("CEFALA' DIANA") ~ "CEFALA DIANA",
        COMUNE %in% c("CEFALU'") ~ "CEFALU",
        COMUNE %in% c("CESARO'") ~ "CESARO",
        COMUNE %in% c("CIGLIE'") ~ "CIGLIE",
        COMUNE %in% c("CIMINA'") ~ "CIMINA",
        COMUNE %in% c("CIRIE'") ~ "CIRIE",
        COMUNE %in% c("CIRO' MARINA") ~ "CIRO MARINA",
        COMUNE %in% c("CITTA' DELLA PIEVE") ~ "CITTA DELLA PIEVE",
        COMUNE %in% c("CITTA' DI CASTELLO") ~ "CITTA DI CASTELLO",
        COMUNE %in% c("CITTA' SANT'ANGELO") ~ "CITTA SANT'ANGELO",
        COMUNE %in% c("CODOGNE'") ~ "CODOGNE",
        COMUNE %in% c("CASTELFRANCO PIANDISCO'") ~ "CASTELFRANCO PIANDISCO",
        COMUNE %in% c("CONDRO'") ~ "CONDRO",
        COMUNE %in% c("CONTA'") ~ "CONTA",
        COMUNE %in% c("CUORGNE'") ~ "CUORGNE",
        COMUNE %in% c("DOBERDO' DEL LAGO") ~ "DOBERDO DEL LAGO",
        COMUNE %in% c("DOLCE'") ~ "DOLCE",
        COMUNE %in% c("ERBE'") ~ "ERBE",
        COMUNE %in% c("FENEGRO'") ~ "FENEGRO",
        COMUNE %in% c("FIAVE'") ~ "FIAVE",
        COMUNE %in% c("FIE' ALLO SCILIAR") ~ "FIE ALLO SCILIAR",
        COMUNE %in% c("FORLI'") ~ "FORLI",
        COMUNE %in% c("FORZA D'AGRO'") ~ "FORZA D'AGRO",
        COMUNE %in% c("FOSSO'") ~ "FOSSO",
        COMUNE %in% c("FRAZZANO'") ~ "FRAZZANO",
        COMUNE %in% c("GAMBOLO'") ~ "GAMBOLO",
        COMUNE %in% c("GUALTIERI SICAMINO'") ~ "GUALTIERI SICAMINO",
        COMUNE %in% c("LUSIGLIE'") ~ "LUSIGLIE",
        COMUNE %in% c("MAIERA'") ~ "MAIERA",
        COMUNE %in% c("MALE'") ~ "MALE",
        COMUNE %in% c("MANSUE'") ~ "MANSUE",
        COMUNE %in% c("MASERA' DI PADOVA") ~ "MASERA DI PADOVA",
        COMUNE %in% c("MAZZARA' SANT'ANDREA") ~ "MAZZARA SANT'ANDREA",
        COMUNE %in% c("MAZZE'") ~ "MAZZE",
        COMUNE %in% c("MELICUCCA'") ~ "MELICUCCA",
        COMUNE %in% c("MONDOVI'") ~ "MONDOVI",
        COMUNE %in% c("MONTA'") ~ "MONTA",
        COMUNE %in% c("MONTALDO DI MONDOVI'") ~ "MONTALDO DI MONDOVI",
        COMUNE %in% c("MONTU' BECCARIA") ~ "MONTU BECCARIA",
        COMUNE %in% c("MUGGIO'") ~ "MUGGIO",
        COMUNE %in% c("NARDO'") ~ "NARDO",
        COMUNE %in% c("PALU'") ~ "PALU",
        COMUNE %in% c("PALU' DEL FERSINA") ~ "PALU DEL FERSINA",
        COMUNE %in% c("PANCHIA'") ~ "PANCHIA",
        COMUNE %in% c("PATU'") ~ "PATU",
        COMUNE %in% c("PETRONA'") ~ "PETRONA",
        COMUNE %in% c("PIOVA' MASSAIA") ~ "PIOVA MASSAIA",
        COMUNE %in% c("PLATI'") ~ "PLATI",
        COMUNE %in% c("PONTE SAN NICOLO'") ~ "PONTE SAN NICOLO",
        COMUNE %in% c("PORTOBUFFOLE'") ~ "PORTOBUFFOLE",
        COMUNE %in% c("PRELA'") ~ "PRELA",
        COMUNE %in% c("REVO'") ~ "REVO",
        COMUNE %in% c("RICCO' DEL GOLFO DI SPEZIA") ~ "RICCO DEL GOLFO DI SPEZIA",
        COMUNE %in% c("ROCCA CIGLIE'") ~ "ROCCA CIGLIE",
        COMUNE %in% c("ROCCAFORTE MONDOVI'") ~ "ROCCAFORTE MONDOVI",
        COMUNE %in% c("ROE' VOLCIANO") ~ "ROE VOLCIANO",
        COMUNE %in% c("RONCA'") ~ "RONCA",
        COMUNE %in% c("RORA'") ~ "RORA",
        COMUNE %in% c("ROSA'") ~ "ROSA",
        COMUNE %in% c("ROVERE' DELLA LUNA") ~ "ROVERE DELLA LUNA",
        COMUNE %in% c("ROVERE' VERONESE") ~ "ROVERE VERONESE",
        COMUNE %in% c("ROVEREDO DI GUA'") ~ "ROVEREDO DI GUA",
        COMUNE %in% c("SALO'") ~ "SALO",
        COMUNE %in% c("SAN DONA' DI PIAVE") ~ "SAN DONA DI PIAVE",
        COMUNE %in% c("SAN MICHELE MONDOVI'") ~ "SAN MICHELE MONDOVI",
        COMUNE %in% c("SAN NICOLO' DI COMELICO") ~ "SAN NICOLO DI COMELICO",
        COMUNE %in% c("SAN PIETRO DI CARIDA'") ~ "SAN PIETRO DI CARIDA",
        COMUNE %in% c("SANFRE'") ~ "SANFRE",
        COMUNE %in% c("SANTA MARIA HOE'") ~ "SANTA MARIA HOE",
        COMUNE %in% c("SANTA MARIA LA CARITA'") ~ "SANTA MARIA LA CARITA",
        COMUNE %in% c("SANTHIA'") ~ "SANTHIA",
        COMUNE %in% c("SCORZE'") ~ "SCORZE",
        COMUNE %in% c("SECLI'") ~ "SECLI",
        COMUNE %in% c("SERRA RICCO'") ~ "SERRA RICCO",
        COMUNE %in% c("SODDI'") ~ "SODDI",
        COMUNE %in% c("SORGA'") ~ "SORGA",
        COMUNE %in% c("TEMU'") ~ "TEMU",
        COMUNE %in% c("TORRE MONDOVI'") ~ "TORRE MONDOVI",
        COMUNE %in% c("TRAVACO' SICCOMARIO") ~ "TRAVACO SICCOMARIO",
        COMUNE %in% c("TRINITA'") ~ "TRINITA",
        COMUNE %in% c("VESTIGNE'") ~ "VESTIGNE",
        COMUNE %in% c("VIALFRE'") ~ "VIALFRE",
        COMUNE %in% c("VIGANO'") ~ "VIGANO",
        COMUNE %in% c("VIGGIU'") ~ "VIGGIU",
        COMUNE %in% c("PATERNO'") ~ "PATERNO (CT)",
        COMUNE %in% c("VILLANOVA MONDOVI'") ~ "VILLANOVA MONDOVI",
        COMUNE %in% c("VIU'") ~ "VIU",
        COMUNE %in% c("ZANE'") ~ "ZANE",
        COMUNE %in% c("ZERBOLO'") ~ "ZERBOLO",
        COMUNE %in% c("ZOPPE' DI CADORE") ~ "ZOPPE DI CADORE",
        COMUNE %in% c("MAZZARRA' SANT'ANDREA") ~ "MAZZARRA SANT'ANDREA",
        COMUNE %in% c("MERI'") ~ "MERI",
        COMUNE %in% c("RODI' MILICI") ~ "RODI MILICI",
        
        str_trim(COMUNE) == "MONTECCHIO" ~ "MONTECCHIO",
        str_trim(COMUNE) == "SAN MARCELLO" ~ "SAN MARCELLO",
        str_trim(COMUNE) == "SANT'ANGELO IN VADO" ~ "SANT'ANGELO IN VADO",
        str_trim(COMUNE) == "SOLERO" ~ "SOLERO",
        str_trim(COMUNE) == "PIAN DI SCO" ~ "CASTELFRANCO PIANDISCO",
        str_trim(COMUNE) == "IVANO-FRACENA" ~ "CASTEL IVANO",
        str_trim(COMUNE) == "CIANO D'ENZA" ~ "CANOSSA",
        str_trim(COMUNE) == "MOSSO" ~ "VALDILANA",
        str_trim(COMUNE) == "RONCHI DEI LEGIONARI" ~ "RONCHI DEI LEGIONARI",
        TRUE ~ COMUNE
      )
    )
}
