# ==========================================================
# parties.R
# Creates a mapping between political parties and ideology
# categories (Conservative, Progressive, Other).
# Output: party_ideology_df saved to a_microdata/
# ==========================================================

stopifnot(exists("A"))

party <- c(
  # HISTORICAL
  
  # Conservative
  "DC", "MSI", "BLOCCO NAZIONALE", "P.NAZ.MON.ALL.D.LAV.", "P.NAZ.MONARCHICO", "P.MONARCHICO POP.", "PAPI", "PPST-PPTT", "PPST", "PPTT",
  "PDIUM", "PLI", "MOV.NAZ.DEM.SOC.", "UN.MOV.FEDERALISTI", "BLOCCO POP.UNIONISTA", "FR.DEGLI ITALIANI", "FR.ANTIBOLSCEVICO IT", 
  "FR.UN.ANTICOM.RIS.N.", "GR.POL.LA DESTRA", "FR.UOMO QUALUNQUE", "P.PATRIA E LIBERTA'", "M.CAT.IND.PAX JUSTIT", "P.MONARCHICO NAZ.IT.",
  "LISTA MONARCHICA", "ALL.DEMOC.NAZIONALE", "CENTRO POLITICO IT.", "P.CRIST.MILITANTE", "P.VOLONTA'NAZIONALE", "P.CAT.RIS.NAZ.CPI",
  "M.COMB.IT-FR.RIN.NAZ", "PART.MON.NAZ.", "AV.NAZ.", "MOV.POP.IT.", "NUOVA REPUBBLICA",  "SACRO IDEAL.MONDO", "FR.NAZ.SIC.", "CONF.IT.LIBERI SIND.",
  
  
  # Progressive
  "FR.DEMOCR.POPOLARE", "UNITA' SOCIALISTA", "PCI", "PSI", "PSDI", "PRI", "PSIUP", "UN.SOCIAL.INDIP.", "PARTITO CRISTIANO SOCIALE",
  "PS D'AZ.", "PC.INTERNAZIONALISTA", "FR.DEM.PROG.REPUB.", "P.DEMOLABURISTA IT.", "PCS (MARX.-LEN.)", "PC(MARX-LEN)IT", "PRI-P.RAD.",
  "P.ESISTENZIALISTA IT", "P.ESISTENZIALISTA UN", "P.RADICAL SOCIALISTA", "MOV.POL.LAV.", "M.FEMMINILE IT.", "STELLA ROSSA-R.S.",
  "UNITA'POPOLARE", "COMUNITA'", "IND.SIN.", "P.UN.SOCIALE IT.", "FED.AUT.SOCIALDEM.IT", "MOV.INDIP.DIVORZISTI", "P.SOC.SICILIANO",
  "RINN.SOC.", "PART.LAB.IT.", "PSU", "P.RAD", "MOV.SOC.", "SOCIALDEMOCRAZIA", "P.COM.RIVOL.", "P.PROG.UNSIPO", "RIS.POP.", "PART.DEM.PROG.",
  "PST.PROG.SOC.", "MANIFESTO", 
  
  # Other
  "P.CONTADINI D'ITALIA", "CONC.NAZ.COMBAT.UNIT", "ALTRE LISTE", "P.DEM.IND.PENSIONATI", "P.INDIPENDENTE CONTADINI",
  "AS.NAZ.CONG.DIS.GUER", "CONC.RUR.IND.AOSTA", "RAGGRUP.POP.ITALIANO", "MAGLIO", "M.NAZ.SIN.DAN.GUERRA", "LEGA SARDA", "IND",
  "UV", "MOVIM.AUT.REG.-M.A.R.P.", "UNIONE TRIESTINA", "UN.NAZ.DEM.IMP.PUB.", "P.NETTISTA ITALIANO", "P.NAZIONALI FEDERATI",
  "MOV.SOC.CRISTIANO",  "P.FEDERALISTA IT.", "M.GARIB.PART.D'ITALIA", "P.UNIONE NAZIONALE", "P.NAZIONALE LAVORO", "FR.DELL'INDIPENDENZA",
  "AUT.PIEMONT-MOV.VIL.",  "MOV.PRO PENSIONATI", "FR.UNICO SOLDATO IT.", "CONC.EUROPEA DEMOC.", "L.UNIT.SLOV.", "MOV.ECONOMICO IT.SOC",
  "P.IT.MUT.INV.GUERRA", "MOV.NAZIONALE IT.", "MOV.AZIONE-RINNOVAM.", "CONC.UNITA'RURALE", "MOV.POL.CATT.IT.", "MOV.IND.TLT", "UN.NAZ.SAL.PUB.",
  "MOV.COLT.E SAL.", "PART.SOC.CRIST.", "UNIONE SLOVENA", "PART.NAZ.MUT.COMB.IT", "RAGGR.ITAL.", "PART.ORD.ECON.", "PART.AGRICOLTORI", "RAG.VOL.\"T\"",
  "DC-UV-RV-PSDI", "DEM.POP.", "AZ.CR.POP.", "RINN.DEM.NAZ.", "UN.FORZE DEM.", "MOV.UNITA'D'IT.",
  
  # CURRENT 2018 
  
  # Conservative
  "LEGA", "FORZA ITALIA", "FRATELLI D'ITALIA CON GIORGIA MELONI", "FRATELLI D'ITALIA", "NOI CON L'ITALIA - UDC", "CASAPOUND ITALIA",
  "ITALIA AGLI ITALIANI", "BLOCCO NAZIONALE PER LE LIBERTA'", "IL POPOLO DELLA FAMIGLIA", "GRANDE NORD", "FI -FRAT. D'IT. -MOV.NUOVA VALLE D'AOSTA",
  
  # Progressive
  "MOVIMENTO 5 STELLE", "PARTITO DEMOCRATICO", "LIBERI E UGUALI", "+EUROPA", "ITALIA EUROPA INSIEME", "CIVICA POPOLARE LORENZIN",
  "SVP-PATT", "POTERE AL POPOLO!", "PARTITO COMUNISTA", "PARTITO VALORE UMANO", "10 VOLTE MEGLIO", "PER UNA SINISTRA RIVOLUZIONARIA",
  "PARTITO REPUBBLICANO ITALIANO - ALA", "PD-UV-UVP-EPAV",
  
  # Other
  "AUTODETERMINATZIONE", "LISTA DEL POPOLO PER LA COSTITUZIONE", "PATTO PER L'AUTONOMIA", "SIAMO", "RINASCIMENTO MIR", "ITALIA NEL CUORE",
  "POUR TOUS PER TUTTI PE TCHEUT", "RISPOSTA CIVICA"
)

ideology <- c(
  rep("Conservative", 37),
  rep("Progressive", 41),
  rep("Other", 51),
  rep("Conservative", 11),
  rep("Progressive", 14),
  rep("Other", 8)
)

party_ideology_df <- tibble::tibble(
  PARTY = party,
  IDEOLOGY = ideology
)

SAVE(dfx = party_ideology_df, pattdir = A)
